version: '3.8'

services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      API_URL: /swagger.yaml
      BASE_URL: /
    env_file: .env
    volumes:
      - ../swagger.yaml:/usr/share/nginx/html/swagger.yaml
      - ../components:/usr/share/nginx/html/components
      - ../paths:/usr/share/nginx/html/paths
    ports:
      - 3200:8080