openapi: 3.1.0
info:
  title: カルタグラフ
  description: カルタグラフ用API
  version: 0.0.1
  contact:
    name: hibohiboo
    url: https://kotatool.vercel.app/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: "{{OutputApiUrl}}"
paths:
  /users:
    $ref: ./paths/sample-users.yml
  /users/{user_id}:
    $ref: ./paths/sample-users-by-id.yml
  /scenario:
    $ref: ./paths/cartagraph.yml

components:
  schemas:
    AccessNumber:
      $ref: ./components/schemas/access-count.yml#/AccessNumber
    User:
      $ref: ./components/schemas/sample/user.yml
    UserInput:
      $ref: ./components/schemas/sample/user_input.yml
  securitySchemes:
    OAuth2:
      $ref: ./components/schemas/oauth2.yml
