spectaql:
  logoFile: ./fixtures/logo.png
  faviconFile: ./fixtures/favicon.png

introspection:
  schemaFile: ./data/schema-cartagraph.gql
  metadataFile: ./data/metadata.json
  dynamicExamplesProcessingModule: ./customizations/examples

info:
  title: CarTaGraph API Reference
  description: Hasura への 問い合わせクエリ
  termsOfService: https://www.example.com/terms
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://example.com/graphql
    description: Production
    production: true
